spring:
  datasource:
    url: jdbc:mysql://db.mysql:3366/user_center
    hikari:
      username: root
      password: Jc1207
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos.han:8848 #不要加http
        service: user-center
logging:
  level:
    com.itmuch.usercenter: debug