spring:
  datasource:
    dynamic:
      hikari:
        connection-test-query: SELECT 1
      primary: master
      datasource:
        master:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://158.247.221.226:3369/user_center?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
          username: "root"
          password: "Jc1207"
          hikari:
            max-pool-size: 10
            min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.itmuch.usercenter.domain
  global-config:
    db-config:
      id-type: id_worker
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
    datacenter-id: ${nodeId:${spring.nodeId:1}}
    worker-id: ${nodeId:${spring.nodeId:1}}
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null