spring:
  datasource:
    url: jdbc:mysql://db.mysql:3366/user_center
    hikari:
      username: root
      password: Jc1207
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.itmuch.usercenter: debug